In [23]:
import numpy as np

data_set = np.array([
    [0.3, -1.2, 0.5, 0.9],
    [0.7, -2.7, 0.6, 0.1],
    [0.3, 0.01, 0.47, 2],
    [0.5, 2.2, 0.11, 3.0],
    [0.12, -0.7, 0.15, 0.25]
])
vec = np.array([0.6, -1.5, 0.3, 0.2])
vec_len = np.linalg.norm(vec)
vec_len

np.float64(1.6552945357246849)

In [24]:
vec_norm = vec / vec_len
vec_norm

array([ 0.36247326, -0.90618314,  0.18123663,  0.12082442])

In [25]:
vec_norm_len = np.linalg.norm(vec_norm)
vec_norm_len

np.float64(1.0)

In [26]:
# data_set_len = np.linalg.norm(data_set)
# data_set_len
data_set_lens = np.linalg.norm(data_set, axis=1, keepdims=True)
data_set_lens

array([[1.60934769],
       [2.85482048],
       [2.07629478],
       [3.75527629],
       [0.76772391]])

In [27]:
data_set_norm = data_set / data_set_lens
data_set_norm

array([[ 0.18641093, -0.74564372,  0.31068488,  0.55923279],
       [ 0.24519931, -0.94576875,  0.21017083,  0.03502847],
       [ 0.14448815,  0.00481627,  0.22636478,  0.96325436],
       [ 0.133146  ,  0.58584238,  0.02929212,  0.79887597],
       [ 0.15630619, -0.91178611,  0.19538274,  0.3256379 ]])

In [28]:
data_set_norm_len = np.linalg.norm(data_set_norm, axis=1, keepdims=True)
data_set_norm_len

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [29]:
similarities = data_set_norm @ vec_norm
similarities

array([ 0.8671352 ,  0.98824083,  0.2054189 , -0.3807861 ,  0.95765754])

In [30]:
best_index = np.argmax(similarities)
best_index

np.int64(1)